/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualRouteImport } from './routes/visual'
import { Route as TasteRouteImport } from './routes/taste'
import { Route as TactileRouteImport } from './routes/tactile'
import { Route as ScentRouteImport } from './routes/scent'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as AdminWriteRouteImport } from './routes/admin/write'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const VisualRoute = VisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => rootRouteImport,
} as any)
const TasteRoute = TasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => rootRouteImport,
} as any)
const TactileRoute = TactileRouteImport.update({
  id: '/tactile',
  path: '/tactile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScentRoute = ScentRouteImport.update({
  id: '/scent',
  path: '/scent',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/admin/write',
  path: '/admin/write',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/guestbook': typeof GuestbookRoute
  '/scent': typeof ScentRoute
  '/tactile': typeof TactileRoute
  '/taste': typeof TasteRoute
  '/visual': typeof VisualRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/guestbook': typeof GuestbookRoute
  '/scent': typeof ScentRoute
  '/tactile': typeof TactileRoute
  '/taste': typeof TasteRoute
  '/visual': typeof VisualRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/guestbook': typeof GuestbookRoute
  '/scent': typeof ScentRoute
  '/tactile': typeof TactileRoute
  '/taste': typeof TasteRoute
  '/visual': typeof VisualRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audio'
    | '/guestbook'
    | '/scent'
    | '/tactile'
    | '/taste'
    | '/visual'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/write'
    | '/posts/$slug'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audio'
    | '/guestbook'
    | '/scent'
    | '/tactile'
    | '/taste'
    | '/visual'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/write'
    | '/posts/$slug'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audio'
    | '/guestbook'
    | '/scent'
    | '/tactile'
    | '/taste'
    | '/visual'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/write'
    | '/posts/$slug'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AudioRoute: typeof AudioRoute
  GuestbookRoute: typeof GuestbookRoute
  ScentRoute: typeof ScentRoute
  TactileRoute: typeof TactileRoute
  TasteRoute: typeof TasteRoute
  VisualRoute: typeof VisualRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminWriteRoute: typeof AdminWriteRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual': {
      id: '/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taste': {
      id: '/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof TasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactile': {
      id: '/tactile'
      path: '/tactile'
      fullPath: '/tactile'
      preLoaderRoute: typeof TactileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scent': {
      id: '/scent'
      path: '/scent'
      fullPath: '/scent'
      preLoaderRoute: typeof ScentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/admin/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AudioRoute: AudioRoute,
  GuestbookRoute: GuestbookRoute,
  ScentRoute: ScentRoute,
  TactileRoute: TactileRoute,
  TasteRoute: TasteRoute,
  VisualRoute: VisualRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminWriteRoute: AdminWriteRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
